### ISSUE TITLE
Focused (NodeBots) session for May

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#136]
I was chatting with @emilyrose about leading a focused session, possibly related to NodeBots and/or node+hardware. This sounds fun to me. Let's discuss. 

FYI: May's event will land on [NodeSchool International Day](http://nodeschool.io/international-day/) which is Saturday May 21st.

**Comment by TheAlphaNerd** [comment]
Super into this!

**Comment by cantremember** [comment]
i think the kids will find that totes sexy

**Comment by teone** [comment]
Would be cool to play with some physical devices, it's a long time I want a tessel!

**Comment by llkats** [comment]
Sounds fun to me! A "how to get started" but for hardware/nodebots type of session would be probably be thematic for our event.

**Comment by emilyrose** [comment]
Yep! I can bring the hardware and curriculum! 😸 

Any ideas for specific projects? I can put together kits for just about anything within reason!

**Comment by emilyrose** [comment]
I'd like to focus on micro controllers and getting started with "IoT" by way of NodeBots!

**Comment by llkats** [comment]
As long as we can set expectations for attendees and spread the word ahead of time, you can pretty much decide what you'd like to focus on and take the session where your interests lead you. IoT via NodeBots and microcontrollers sounds perfect to me! 😁

**Comment by emilyrose** [comment]
@llkats great!

I'll need to know the approximate # of attendees to expect, and how long we will have to work together!

**Comment by Fauntleroy** [comment]
@llkats Will we have a separate ticket allotment for the focused session?

**Comment by jedireza** [comment]
@Fauntleroy it was helpful for previous focused sessions, I think we'll do it again.

**Comment by llkats** [comment]
Yeah, definitely have a separate ticket allotment, especially since we'll have limited hardware. The space where we hold the focused sessions can accommodate a good number of people (I forgot the number exactly, @jedireza you remember what it is?) but I think for a hardware-focused session, we should keep the number somewhere around 20, 30 at max, maybe?

@emilyrose sorry to make you define All The Things, but is there a number you're most comfortable with, or have enough hardware for? We'll defer to your expertise on that one, but space should not be an issue. We'll dedicate 2-3 mentors to your session so they can lend a hand to peeps with questions. Also there will be a projector, screen, and podium for your use.

The event runs for 4 hours with a break for pizza, and as long or short you want to make your session within that time-frame is fine with us. For example, if you want to lead for an hour and let people hack for an hour, that'd be fine. You can fill up the whole time too, if you want! But people can always hack on workshoppers if you want to pack up the hardware early.

@jedireza @Fauntleroy we should remember to make a special call for mentors with hardware experience.

**Comment by Fauntleroy** [comment]
I wouldn't have more than 20 people in the back room (maybe even 15?) working with hardware, though we might have to release 30 tickets to get 20 to actually show up.

**Comment by llkats** [comment]
Just erring on the side of generosity, I guess. It's up to what @emilyrose is comfortable with!

I had a really good turnout with my git-it session, and if we do have any no-shows, I'm pretty sure that people from the general group would love to step in.

**Comment by emilyrose** [comment]
20-30i sounds just perfect! 😸 

I'd like to plan on doing a guided presentation of about 45 minutes tops to cover the basics, and then spend the rest of the time letting people engage in self-guided hacking. We will have curriculum and components for a basic project which includes an RGB LED and a momentary switch. I will walk through each of the steps for getting things built & integrated. From there, participants will be encouraged to branch out with various additional components that I will supply (sensors, servos, etc.) I'd also like to set aside about 45 minutes at the end to allow folks to demo what they've built.

Let me know what you think about this plan. I'm happy to adapt if you have suggestions!

**Comment by jedireza** [comment]
Perfect!

**Comment by llkats** [comment]
Yes, indeed! Sounds great!

**Comment by emilyrose** [comment]
Yay! I'm looking forward to it!

**Comment by jedireza** [comment]
[Mentor registration](https://github.com/nodeschool/sanfrancisco/issues/137) is open and [ticket registration](https://ti.to/nodeschoolsf/may-21st-2016) is live. Closing this issue now. 👍
