### ISSUE TITLE
Focused session for September

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#154]
What should the focused session be about in September?

**Comment by noffle** [comment]
I remember us talking yesterday about all of the nice terminal tricks and fundamentals that new Noders could benefit from knowing. I could talk about these and how to become a command line star :star2:.

**Comment by feross** [comment]
@noffle I like that 👍

**Comment by teone** [comment]
@noffle look a good idea and quite an unconventional focused session, I like it!

**Comment by jedireza** [comment]
I do like this idea. Let's try to flesh it out a bit. Here are some of my thoughts:

 - I'm curious about defining prerequisites to this session. Will you cover basic shell scripting?
 - What curriculum structure could we define?
  - Would the idea of [dotfiles](http://dotfiles.github.io/) be part of the curriculum?
 - Will this apply to Windows, macOS and Linux users? Or just a subset? Or just one?
 - As some of us know, the world of shells is opinionated. Will there be any preference to bash vs [zsh](http://www.zsh.org/) vs [fish](https://fishshell.com/) vs _[insert favorite shell]_?

@llkats what are your thoughts? IIRC you did a (blog post or talk) comparison of shells not to long ago. Is that right?

**Comment by llkats** [comment]
Hiii~~

I love the idea of a talk about command-line tips focused on Node. As @jedireza points out, it's really important to define the focus for attendees since platforms and shells are extremely varied. I did give a talk on shells at OSBridge 2015 ([here's a shameless link to my slides and video](http://llkats.github.io/osbridge-2015-slides/)). Maybe it could focus on cross-platform (insofar as possible) commands, build tools, and npm commands for Node? I'm of course happy to contribute content and assistance!

**Comment by noffle** [comment]
Thanks for the support! :tada:   I think I'd like to see a focus on two things:

1. teaching the fundamentals of using the shell
 - brief history
 - setup (linux/mac: easy; windows: cygwin???)
 - basic commands (mkdir, ls, cd, mv, cp, etc)
 - common programs (grep, sed, curl, less)
 - how to compose programs using pipes (curl foo.com | sed '...' | less)
 - how to reuse your compositions (write a shell script, chmod +x, $PATH)
 - shell shortcuts (prev/next command, search command history, back/fwd
   word, kill line back/fwd, using shell comments to save commands for
   later, ...)

2. using those fundamentals to manipulate your node project from the shell
 - what is npm
 - npm module lifecycle commands (init, package.json, info, version, publish)
 - helpful unix-y cli modules from npm (readme, ecstatic, pkginit, hcat/scat, tslide, common-readme, cyberhobo)

Content for the first part would probably be similar to the beginning of @llkats' talk, and also [the cyberwizard unix intro]( - intro to the shell / bash: https://github.com/cyberwizardinstitute/workshops/blob/master/unix.markdown).


> I'm curious about defining prerequisites for this session. Will you cover basic shell scripting?

Yes! Ideally the only requirement is having used Node before, but maybe even that wouldn't be necessary.

> Will this apply to Windows, macOS and Linux users? Or just a subset? Or just one?

Linux and OSX are similar enough, and both have a terminal emulator pre-packaged. Windows might be more difficult. Cygwin? We'd need to investigate further.

> As some of us know, the world of shells is opinionated. Will there be any preference to bash vs zsh vs fish vs [insert favorite shell]? If zsh is covered, will oh-my-zsh get covered?

I think it would be best to keep opinions on the different kinds of shells to a minimum. Bash is powerful enough to do all of the important things, and everyone can expect some reasonably recent version of it to be installed on their machine already. Glitzing your shell might be best left as an exercise to the reader, once they grok the fundamentals.


What do y'all think?

**Comment by jedireza** [comment]
> Linux and OSX are similar enough, and both have a terminal emulator pre-packaged. Windows might be more difficult. Cygwin? We'd need to investigate further.

I agree. It's fine to limit it to macOS and Linux, we just need to call it out for Windows users.

> What do y'all think?

Very cool. Are you planning on creating a slide deck to progress through the session? Do you think 3ish hours is enough time to cover all this material? And do you think there will be time for people to play around with what they learn at their own pace and ask questions?

**Comment by noffle** [comment]
> I agree. It's fine to limit it to macOS and Linux, we just need to
> call it out for Windows users.

I can spend a bit of time researching what's involved.

In my experience I've been frustrated by presenters who don't consider
Windows users. At one workshop I was at, surrounded by shiny expensive
Macs, the one Windows user asked how to get the example working on their
machine. The presenter made a joke about Windows at their expense
instead of helping, but I was able to spend the session with them
getting it figured out.

> Very cool. Are you planning on creating a slide deck to progress
> through the session? Do you think 3ish hours is enough time to cover
> all this material? And do you think there will be time for people to
> play around with what they learn at their own pace and ask questions?

I'm not sure how long it will take. Probably a couple of hours depending
on the level of detail. I may take use the slides from the cyberwizard
institute unix intro with some modifications
(https://github.com/cyberwizardinstitute/workshops/blob/master/unix.markdown).

I wonder how much this session even needs to be "led" versus students
moving at their own comfort level. It might work out well as just a room
of relative self-study, with the knowledge that their peers and mentors
are all focused exclusively on the same material. There may be more
concurrency challenges in doing "okay, now type 'cp foo ../bar'" in
lock-step than in just addressing questions as they come up.

**Comment by noffle** [comment]
Just so I know how to prepare: am I doing the focused session? Do we have a date for September @jedireza? I'm out of country later in the month.

**Comment by llkats** [comment]
@noffle I'm planning on September 24th, the usual last Saturday thing. Would that day still work for you?

**Comment by llkats** [comment]
@noffle we have confirmation for the 24th!

**Comment by noffle** [comment]
It turns out I'm going to be out of the country some time later this month. Since I'm not sure whether I'll be here on the 24th, it's probably safer to schedule in another workshop for September, and come back to this one for October or November.

**Comment by Trott** [comment]
I'd be happy to try to do a http://nodetodo.org/ session.

If we go with that, and even if not, I'd kind of like to do it ahead of time with any mentors who haven't already contributed to Node.js. (Doing it remotely is fine.) So, uh, any mentors interested in getting a contribution into Node.js core, let me know!

**Comment by llkats** [comment]
Sorry it's not working out this month @noffle, but let's get you on a future one soon!

@Trott thanks for jumping in to volunteer!! Would love to have you fill in. I'm happy to be a guinea pig for the session, too. If anyone else wants to jump in as well, the more the merrier 😄

**Comment by jedireza** [comment]
I like it @Trott!

**Comment by Trott** [comment]
Here's the Getting Setup part. For mentors, it would be great if they could do this ahead of time. 

## Getting Setup

* Create a GitHub account (if they don't already have one)
* Go to https://github.com/nodejs/node and use the "Fork" button to fork their own repo of node
* On the page for their own fork, use the "Clone or download" button and copy the URL for cloning to their clipboard
* On the command line, in their home directory or a directory they have for projects like this, run:  `git clone <paste that URL here!>`
* When that is done: `cd node`
* `git remote add upstream https://github.com/nodejs/node.git`
* Follow the instructions at https://github.com/nodejs/node/blob/master/BUILDING.md to build Node.js. (Skip the `[sudo] make install` command listed in that doc! We're just trying to build, that's all. If you can  `make test` on UNIX-like operating systems or `vcbuild test` on Windows, then you are all set!)

So, it would be great if interested folks can try to get as far with that as they can before the session. If OS X users have to install Xcode (which they don't need to use directly, but associated tools need to be there for the build tasks) at the session, they're not going to get very far because downloading and installing Xcode can take a very long time.

But we'd also want to note (and maybe we can verbally say this in the welcoming remarks at the event) that if you ran into trouble getting that far, it's OK, we're here to help. This is where it would be great if all the mentors in the focused session could at least get that far. Also, we'll want to have at least one mentor who has done it on Windows.

The dark secret is that all that setup stuff is really the hard part. After that, it's just refactor some JavaScript that could be a little better (I have a bunch of instances ready to hand out like candy), and follow the instructions for commit message formats and stuff like that. And suddenly you're a contributor. Congratulations!

**Comment by Trott** [comment]
@llkats and anyone else interested in this: Try to follow those setup instructions. Once successful (or once hitting a roadblock), let me know and I'll get the next steps to you. (I've never actually written this stuff out, so it's helpful to force me to document it like this!)

**Comment by llkats** [comment]
@Trott I'll give it a try this weekend and report back to you 😊

**Comment by Trott** [comment]
@llkats Did you get a chance to do those steps? Anyone else?

**Comment by tlhunter** [comment]
@Trott the steps worked good for me. We'll definitely want people to clone repo's and install dependencies beforehand.

**Comment by paulgrock** [comment]
@trott do you need help running this?

**Comment by Trott** [comment]
@paulgrock Yes, please! Go volunteer to mentor in https://github.com/nodeschool/sanfrancisco/issues/156 !

**Comment by llkats** [comment]
@Trott I'm afraid I over-promised on getting to this before I went to Node Interactive. I'm still trying to finish my talk, so I don't think I will be able to pitch in on this before Monday the 19th. I hope this doesn't deter you from committing to the focused session -- I'm positive you're going to be ready and awesome. Sorry about dropping the ball here!

**Comment by Trott** [comment]
@llkats No worries! Have a great trip and a great talk! Get to it when you get to it. 

If you go to the Code & Learn session they're having at Node Interactive EU, it might bear some similarities. You might also be able to provide some "definitely do X" or "whatever you do, don't do Y" type of recommendations based on your experience.

**Comment by Trott** [comment]
@bengl might be a good person to have on board for this.

**Comment by bengl** [comment]
![](http://static1.squarespace.com/static/53275e12e4b0eeecbb68c86c/532761eae4b0fb8bb1f00297/5329f5a8e4b0c530c2472a14/1395258792715/I'M+ON+BOARD+graphic-small.jpg?format=1000w)

**Comment by llkats** [comment]
@Trott - I installed and built node! Seemed easy enough for me. One thing that I found slightly confusing was "skip the [sudo] make install" instruction -- I didn't see that command until the bottom of the readme and almost didn't run `make` at all.

Would it be possible to list what commands to run and why? Or at least the helpful ones to run before the workshop. The `make` step took a really long time, as you probably know. If some people have already run through these steps, but others have not, we should probably have something for people to do while they're either building or waiting for others to build.

We could try putting the information about downloading and building Node in the pre-event email that we usually send. I can make sure that gets sent on Thursday, if you'd like to put in extra information about your session to try and get attendees on board before the event.

Please let me know if there's anything else I can do to support you in this!

**Comment by Trott** [comment]
@llkdats The caution against `sudo` was for a previous version of that doc. I'll update the gist to remove that caution. Thanks! That's exactly the type of thing I want to identify before the session rather than during it. :-D

If it's all right with you, I think we can include a link to the gist in the email. We can include some text that says it's OK if you don't successfully complete it, but please try.

**Comment by llkats** [comment]
@Trott just sent the email to the attendees! Hopefully it gets people going and also maybe boosts signups too.

**Comment by bengl** [comment]
@Trott I've always had trouble getting node to compile on Windows 10, so I'm gonna give it a nother go tomorrow morning, so that hopefully I'll have some answers for any Windows folks in the room.

**Comment by llkats** [comment]
Thank you @Trott!!! And to @bengl and @paulgrock for A+ mentorship, as well as everyone else who pitched in. A+ job all around ❤️  🎉
