### ISSUE TITLE
Focused Session for October - Nodebots

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#159]
Organizational thread for October's focused session! @nebrius, will we be hosting NodeBots in October? Hope so! 👻

**Comment by BerkeleyTrue** [comment]
Node powered motion activated dancing skeletons!

**Comment by nebrius** [comment]
I'm in! Halloween themed hardware hacks...hmmm...let  me think on this idea :)

**Comment by nebrius** [comment]
Ok, so here's what I've got for this session. I'm [running a workshop](https://github.com/nebrius/nodeconfeu2016) at NodeConf EU next week, and it just so happens I'll still have all of the hardware. Lights are super flexible (and can be made orange!), and it may even be possible to to incorporate sound into the build if I can find time to investigate 😀

**Comment by llkats** [comment]
@nebrius also please let us know if you need any 💲 💵  for hardware/equipment too, I know @tlhunter was talking about possible sponsorship in #157

**Comment by nebrius** [comment]
Hmm, I have an idea on funding, I'll hop over to #157!

**Comment by nebrius** [comment]
I ran the workshop at NodeConf EU and it was a success! I have a question though about running it for NodeSchool SF. The workshop uses Raspberry Pi's that need _wired_ Ethernet to work. I realize this is late in the game, but do we know if we could get a switch+cables from Mozilla for the workshop?

If not, I can switch to using Arduino's instead of Pis and using my [Node Summit 2016](https://github.com/nebrius/nodesummit2016) workshop instead, which is pretty similar. The downside to the node summit workshop is that people don't write the code to control LED's directly, it relies instead on sending messages to custom firmware to do it, so it's not as fun.

**Comment by jedireza** [comment]
@nebrius how many Ethernet cables/connections would we need (20-30)? Do they need to be connected to the Internet?

**Comment by nebrius** [comment]
@jedireza I have 25 RPis, and each would need a connection, assuming of course there are 25 people who want to participate. They don't need to be Internet connected, but laptops on the wifi network would need to be able to connect to them. I have a wireless router I could bring so that we can set up a  wifi AP connected to the switch if connecting the switch to the intranet isn't possible.

**Comment by jedireza** [comment]
So we'd need a local area switch with 26 ports and 26 cables. Is that right?

**Comment by nebrius** [comment]
Ideally yeah, although if all we have is a 24 port switch, that's close enough.

**Comment by jedireza** [comment]
Ok I'll see what I can do.

**Comment by jedireza** [comment]
Looks like I got a hold of an EX2200 48 port switch and IT said they have Ethernet cables (~5ft).

**Comment by nebrius** [comment]
Excellent, thank you @jedireza! That should work perfectly. I'll bring one of my own long ethernet cables and the wireless router, just in case we need to unexpectedly get creative :)

**Comment by llkats** [comment]
Thanks!!!
