### ISSUE TITLE
Workshop Proposal: Creating Serverless APIs using GraphQL and Apollo Server

### ISSUE THREAD

**Issue by ErickWendel** [nodeschool/sanfrancisco#259]
Hi guys!! Are you fine? 

I was talking with @nebrius about to create a workshop teaching how to create a complete Serverless API using GraphQL and Apollo Server. I did something like that teaching about Docker, Kubernetes, and Hapi.js (creating APIs too). When I did these workshops, generally is around 4 hours of class. The attendees will bring their PCs and we will build an application together, where I'll create the examples in my PC  and then they will write the same code in their PCs

**Comment by nebrius** [comment]
I think this sounds like a good workshop idea. One thing to note: in practice you'll have about 3 hours for the workshop, so you may need to trim your workshop to fit.

@Xabadu @tlhunter what do you think about this for a focus session?

**Comment by Xabadu** [comment]
I agree. This sounds like a great topic for a workshop, thanks for volunteering @ErickWendel!. Our next event is on Saturday, February 16th, does that date work for you?

Also, +1 to what Bryan mentioned about the duration. I think trimming it down to 3 hours would be a good move, while also keeping in mind that there will be a food intermission in between (sessions usually start at around 1.30 and we get food around 2.30~ish), so it would be good to take that into consideration for planning as well, since attendees will probably take a 20-30 min break to eat and socialize :)

**Comment by ErickWendel** [comment]
Sure guys :D Count on me.

**Comment by Xabadu** [comment]
Thanks for coming and doing this workshop @ErickWendel. It was a success!
