### ISSUE TITLE
Special git-it Session for August 29th 2015

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#85]
For our next session, I'd love to offer to lead a group in working through @jlord's amazing `git-it` workshopper, with a special focus on opening issues and contributing changes to the `nodeschool` workshoppers themselves. 

In workshopper fashion, `git-it` is still self-directed, but I would also like to cover topics like: creating issues on a repository, code reviews, and other general skills on how to contribute to open source on github. Right now, I envision this as a more guided session where we all progress through the chapters of `git-it` together, making sure everyone is on the same page. After we have finished, then there will be a talk component where I present on how to create issues and demonstrate how a code review might work on a demo repository, and also discussion and ideas about how contributions could be made to improve Nodeschool workshoppers themselves.

This will be a special session for people who have not contributed to a project on GitHub before. It would occur at the same time as what I'm thinking of as "OG Nodeschool SF" or "OGNSF" (pronounced og-sniff). We will continue to accommodate people who want to work on `javascripting` or `learnyounode`, but because this will be a more focused session, people who interested in `git-it` will move to a separate area to facilitate this workshopper.

Reza and I explored an adjacent room to the room we were in at Mozilla HQ where there are desks and whiteboards and stuff that would be perfect for hosting a more focused meeting. It looked like it could accommodate maybe 20-25 people? Thus, 3-4 mentors who are interested in helping with this session as people work through the exercises would be most appreciated.

Comments? Suggestions? Want to help out? Please let me know here!

Mentors
- [x] @llkats
- [x] @Trott 
- [ ] or you?
- [ ] maybe you?

**Comment by jedireza** [comment]
I love it!! I created a special ticket :ticket: for this to help our attendance predictions. 

https://ti.to/nodeschoolsf/august-29th-2015

**Comment by Trott** [comment]
I'm happy to mentor in the special session. `git-it` is quite possibly the most well-done of all the workshoppers, which is kind of funny because it isn't even about Node. 

If we end up with a lot of front end folks in the room, we could even direct them to the repo for the NodeSchool SF site and ask them to consider implementing something small (e.g., a minor accessibility improvement) or not-so-small (e.g., a photo gallery) and have them submit a pull request for it so they get to use what they learned immediately. 

I like the pull requests for workshoppers idea too. It's probably not hard to find typographical errors that need correcting in a lot of the less-frequently-used workshoppers, so they wouldn't have to learn Node to start in with the pull requests.

Lastly, if there's other people who really want to mentor the special session, I'm happy to mentor over in the general free-for-all area too. Just happy to be a part of things. But I do think this is a good idea and, all things being equal, I guess I'd prefer to be a part of the `git-it` session.

**Comment by llkats** [comment]
Thanks, @Trott! I'm sure we'll float around as necessary in different roles. I wouldn't want to totally confine people to one room or the other, mentors or students; I just think the separation of rooms will help facilitate focusing on the workshopper all together.

I really like your idea about showing them immediate small changes they could make. Maybe we could come up with a few and then brainstorm some ideas as a group that people could then own and tackle.

I forgot to address sign-up, thanks @jedireza!! That's perfect. I'll be sure to tweet some stuff too, and perhaps look at updating the website/ti.to with some more information for anyone who didn't see this issue.

:dancer: :dancers: :tada:

**Comment by jlord** [comment]
So exciting! I'd love any feedback y'all have after doing this! I'm current working on [porting](http://github.com/jlord/git-it-electron) `git-it` over to Electron so it runs as a desktop application and always want to make improvements :sparkles: 

Also want to throw out this GitHub guide on [GitHub Flow](https://guides.github.com/introduction/flow), it has a great diagram that you can click through to explain branching, committing, making a PR and merging. I sometimes put it up on a screen when I talk through that flow with groups.

Also, if anyone is interested we have [Git cheatsheets](https://training.github.com/kit/) here and if you want some real printed versions we could make that happen, too. 

Wish I could be there hanging with y'all! :pizza: :heart:

**Comment by llkats** [comment]
@jlord will totally let you know how it goes! Thank you for all the tips and for creating the workshopper too, I'm excited to get some new peeps into open source. :smile_cat: :tada: :dancers:

**Comment by jedireza** [comment]
The turnout was great. Many thanks to @llkats!!
