### ISSUE TITLE
git-it workshopper feedback

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#90]
Please let me know how it went! Any improvements, what you liked or didn't like - let me know!

**Comment by Trott** [comment]
I loved that you added your own experiences contributing to open source at the end.

**Comment by jimbarrett147** [comment]
Today's session was great! I really enjoyed it and learned a lot. The format and tempo was ideal for somebody starting out with Git. You can tell that there was a huge amount of time, effort and dedication was put into organizing the event. I look forward to the next event! Thanks to all involved.

**Comment by llkats** [comment]
Thank you @Trott and @jimbarrett147 :grinning: :sparkles: :tada:

**Comment by goodbedford** [comment]
@llkats Thanks for leading the workshop, you did really well.  You did a sound a job of managing the flow and getting people help. All the mentors did a good job swooping in to help as well. You additionally had good timing on when to move on, especially when you sensed that not everyone was going to pass the module. Then when you added your personal tips at the end it gave another level of depth to workshop. The two gents I sat next to appreciated the workshop and want to come back.  It seemed like more people asked for help more frequently than I noticed in the past. I already told all my dev friends how enjoyable it was on Saturday.

The anecdote you told about some of your previous contributions to a friends repo was very moving. I know a lot of people who have yet to give to open source. Even with my first small steps, I have to say has been an uplifting experience. You didn't accept my first pull-request but your feedback was very tangible and thoughtful, much different from the code bashing you received in the story. @group everyone was been so great I am completely amazed because it seems so effortless.

**Comment by llkats** [comment]
Thank you for the feedback, @goodbedford, I'm so glad that you found the session useful and enjoyed it! I will be sure to do more in the future. :smile:

**Comment by llkats** [comment]
Seems like that's it for this round. Thanks all!
